version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: spring-boot-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: Pre-purchase
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD : password

  redis:
    image: redis:latest
    container_name: spring-boot-redis
    ports:
      - "6379:6379"