spring:
  datasource:
#    url: jdbc:mysql://localhost:3307/Pre-purchase?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3308/Pre-purchase?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Seoul
    username: root
    password: password

redis:
  host: localhost
  port: 6379

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQ=
  token-validity-in-seconds: 86400

logging:
  level:
    org.springframework.security: DEBUG
